name: "crayon13 set Env test"
run-name: "${{ inputs.env }} 환경으로 ${{ github.ref_name }} 를 배포합니다."

on:
    workflow_dispatch:
        inputs:
            env:
                description: '배포할 환경'
                required: true
                default: 'devel'
                type: choice
                options:
                    - devel
                    - alpha
                    - prod

env:
    AWS_REGION: ap-northeast-2
    AWS_IAM_ROLE: arn:aws:iam::445363019552:role/all_github_action_ecr_upload

jobs:
  init:
    name: initialize
    runs-on: ubuntu-22.04
    steps:
      - id: time
        name: Get current time
        uses: josStorer/get-current-time@v2
        with:
          format: YYYYMMDD-HHmmss
          utcOffset: "+09:00"
      - id: setup_var
        name: Setup Variables
        run: |
          echo "PROFILE=${{ inputs.env }}" >> $GITHUB_ENV
          echo "R_TIME=${{ steps.time.outputs.readableTime }}" >> $GITHUB_ENV
          echo "F_TIME=${{ steps.time.outputs.formattedTime }}" >> $GITHUB_ENV          
      - name: print
        run: |
           echo "PROFILE          : ${{ env.PROFILE }}"
           echo "R_TIME             : ${{ env.R_TIME }}"
           echo "F_TIME             : ${{ env.F_TIME }}"

